### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by smi243** [ThibHlln/smartpy#2]
AttributeError: Module 'smartpy' has no attribute 'Contract'

Tried installing the package repeatedly, yet the same issue occurs.

**Comment by ThibHlln** [comment]
Are you trying to use the Python package relating to SmartPy.io?
If so, please note that this repository has nothing to do with SmartPy.io

**Comment by ThibHlln** [comment]
I would be useful if you could provide a minimal working example (https://en.wikipedia.org/wiki/Minimal_working_example) for your problem, otherwise it is hard to help.

I am guessing that you are trying to use the Python package relating to SmartPy.io, is this correct?
If so, please note that this repository has nothing to do with SmartPy.io

**Comment by ThibHlln** [comment]
Hi @smi243 

Could you provide some follow up on this please?

Thank you.
